version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_edinurf
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data_edinurf:/var/lib/mysql
    networks:
      - internal_edinurf
  drupal:
    image: drupal:9.0.3-fpm-alpine
    container_name: drupal_edinurf
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal_edinurf
      - external_edinurf
    volumes:
      - drupal-data_edinurf:/var/www/html
  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver_edinurf
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - drupal-data_edinurf:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - external_edinurf
networks:
  external_edinurf:
    driver: bridge
  internal_edinurf:
    driver: bridge

volumes:
  drupal-data_edinurf:
  db-data_edinurf:
